# Generated by Django 3.1.1 on 2020-09-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('subject_code', models.CharField(max_length=6)),
                ('credit_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('dept_code', models.CharField(max_length=5)),
                ('year', models.IntegerField()),
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('registration_no', models.IntegerField()),
                ('mobile_no', models.IntegerField()),
            ],
        ),
    ]
