# Generated by Django 3.1 on 2020-08-29 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class', '0001_initial'),
        ('assignment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(verbose_name='Submission Date')),
                ('question1', models.TextField(default='Add Question', null=True, verbose_name='Question 1')),
                ('question1_total_marks', models.PositiveIntegerField(default=1)),
                ('question2', models.TextField(default='Add Question', null=True, verbose_name='Question 2')),
                ('question2_total_marks', models.PositiveIntegerField(default=1)),
                ('question3', models.TextField(default='Add Question', null=True, verbose_name='Question 3')),
                ('question3_total_marks', models.PositiveIntegerField(default=1)),
                ('full_marks', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.class')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1_answer', models.TextField(default='Your Answer', null=True, verbose_name='Question 1 Answer')),
                ('question1_marks', models.PositiveIntegerField(null=True)),
                ('question2_answer', models.TextField(default='Your Answer', null=True, verbose_name='Question 2 Answer')),
                ('question2_marks', models.PositiveIntegerField(null=True)),
                ('question3_answer', models.TextField(default='Your Answer', null=True, verbose_name='Question 3 Answer')),
                ('question3_marks', models.PositiveIntegerField(null=True)),
                ('total_marks_obtained', models.PositiveIntegerField(null=True)),
                ('examQuestions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examquestions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_answer', to='assignment.student')),
            ],
        ),
    ]
